---
title: "Comet Violin plot+scatter"
author: "Marijn Knip"
date: "2/7/2018"
output: html_document
---

Loading data and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())

library(ggplot2)
## library(rstudioapi)
library(ggsignif)
library(ggpubr)
library(doBy)

## setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) not working/necessary for r-markdown

df = read.csv(file.path("data - Figure S2.csv"),
              header=T,
              sep=";",
              stringsAsFactors=F,
              dec = ",",
              colClasses = c("factor","numeric","factor"))

data <- summaryBy(PercentHead ~ Time + Construct, data=df, FUN=c(length,mean,sd))
```

Filtering and formating data.
Left piece in from earlier statistics, but it's inactivated (Apply Kruskal statistical test on both AN and NN data.)
Paragraph to set titles and labels.
Function to extract quartiles and means for plotting.

```{r, echo=FALSE}

#names and titles
legendname1 = "DEX::GFP"
plottitle = ""
plotsubtitle = ""
yaxislabel = "% of DNA in comet head"
xaxislabel = "Time after DEX-induction (hrs)"

```



```{r, echo=FALSE}

## PLOTTING PART
## Plot prep and Violin plot
p1 <- ggplot(df, aes(x=Time, y=PercentHead,fill=Construct))+
       geom_boxplot(
              position=position_dodge(width = 0.85),
              colour = "black",
              outlier.color = "grey50",
              outlier.shape="o")+
    geom_text(data = data, aes(x = Time, y = PercentHead.mean, label = PercentHead.length), 
              size = 5,
              vjust = 0.9)+
      stat_compare_means(method="wilcox.test", 
                         comparisons = list(c("4", "8"), c("2", "8")),
                        ##label.y=105,
                        symnum.args = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 1), symbols = c("***", "**", "*", "ns")),
                        label.sep = ", ",
                        label="p.signif")+
      scale_fill_manual(
                        values=c("#00ff00"),
                        labels = legendname1)+
       scale_y_continuous(breaks=seq(0, 100, 5))+
       labs(
          title =plottitle, 
          subtitle=plotsubtitle,
          y=yaxislabel,
          x=xaxislabel,
          fill="Construct")
p1 

```
```{r, echo=FALSE}
##Setting a theme
p2 <- p1 +  theme(axis.text = element_text(size = 14, face="plain"),
          plot.title = element_text(face = "bold", size = 12, angle = 0, colour = "Black", hjust=0.5),
          plot.subtitle = element_text(face = "italic", size = 14, angle = 0, colour = "Black", hjust=0.5),
          axis.title = element_text(size = 14, angle = 0, colour = "Black"),
          strip.text = element_text(size = 14, angle = 0, colour = "Black"),
          panel.grid.major = element_line(size = 0.5, linetype = 'solid',colour = "#f9f9f9"), 
          panel.grid.minor = element_blank(),
          panel.background = element_rect(fill = "white"), 
          panel.border = element_rect(colour = "black",fill=NA, size=1),
          legend.key = element_blank(),  ## Get rid of the legend box 
          legend.title = element_text(size = 14, face="bold"),
          legend.text = element_text(size = 14, face="italic"))
p2
```

```{r, echo=FALSE}
ggsave(filename = "COMETboxplot-no title.png",plot = p2,width = 8,height = 6,dpi = 600)
ggsave(filename = "COMETboxplot-no title.pdf",plot = p2,width = 8,height = 6,dpi = 600) 
```
